# Generated by Django 4.0.4 on 2022-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_alter_familiares_dni_alter_familiares_hijos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
